env:
  browser: true
  es2021: true
  node: true  

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended

parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true

plugins:
  - react
  - react-hooks

rules:
  no-param-reassign: ["error", { "props": false }]
  no-confusing-arrow: ["error", {"allowParens": true}]
  indent:
    - error
    - 2
  quotes:
    - error
    - single
  semi:
    - error
    - always
  react/prop-types: off
  react/react-in-jsx-scope: off
  react/jsx-uses-react: off
  react/jsx-uses-vars: error

settings:
  react:
    version: detect
